apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: manojjenkinsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: manojjenkinsapp
  template:
    metadata:
      labels:
        app: manojjenkinsapp
    spec:
      containers:
        - name: webapp
          image: webappmanojjenkins:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webapploadbalancer
spec:
  type: LoadBalancer
  selector:
    app: manojjenkinsapp
  ports:
    - port: 80
      targetPort: 5000